
package com.math.utility.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.13
 * Thu Dec 04 11:24:22 CST 2014
 * Generated source version: 2.6.13
 */

@XmlRootElement(name = "addIntegersResponse", namespace = "http://utility.math.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addIntegersResponse", namespace = "http://utility.math.com/")

public class AddIntegersResponse {

    @XmlElement(name = "return")
    private int _return;

    public int getReturn() {
        return this._return;
    }

    public void setReturn(int new_return)  {
        this._return = new_return;
    }

}

